name: Add Label on Milestone Assignment

on:
  issues:
    types:
      - milestoned

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps: 
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ["status: in progress"]
          })
