name: Python Tests

on:
  push:
    branches:
      - main  # Der Workflow wird bei Pushes zum 'main' Branch ausgeführt. Ändere es nach Bedarf.
  pull_request:
    branches:
      - main  # Der Workflow wird auch bei Pull Requests auf den 'main' Branch ausgeführt.

jobs:
  test:
    runs-on: ubuntu-latest  # Der Workflow wird auf der neuesten Ubuntu-Version ausgeführt.
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Diese Action holt den Code des Repositories

    - name: Set up Python
      uses: actions/setup-python@v4  # Diese Action richtet Python ein
      with:
        python-version: '3.9'  # Stelle sicher, dass du die richtige Python-Version verwendest

    - name: Install dependencies
      run: |
        python -m venv venv  # Erstelle eine virtuelle Umgebung
        source venv/bin/activate  # Aktiviere die virtuelle Umgebung
        pip install --upgrade pip  # Aktualisiere pip
        

    - name: Run tests
      run: |
        source venv/bin/activate  # Aktiviere die virtuelle Umgebung
        pytest  # Führe die Tests aus
